### ISSUE TITLE
[품목관리] 스크롤 커스텀(우선순위 하)

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#79]
**Describe the bug**
[품목관리] 스크롤 커스텀(우선순위 하)

**Expected behavior**
디자인형태로 스크롤 커스텀

**Comment by SeonHyungJo** [comment]
참고

```css
/* Scroll Custom */
    ::-webkit-scrollbar {
        width: 8px;
    }

    ::-webkit-scrollbar-button {
        width: 0px;
        height: 0px;
    }

    ::-webkit-scrollbar-thumb {
        background: #fe4c8d;
        border-radius: 8px;
    }
```
